import cloneDeep from 'lodash/cloneDeep'
import { EXTEND } from '@/config/EXTEND'
import { Sub } from '@/lib/Sub'
import { getFileFormat } from '@/lib/index'
import type { TaskData } from '@/config/EXTEND'

export const ASS_KEYS = Object.keys(EXTEND.style)

export const ASS_COLOR
  = /&H([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})/

export function zfill(x: string | number, size: number): string {
  let str = String(x)
  while (str.length < size) str = `0${str}`
  return str
}

export function alphaToNum(val: string): number {
  return Number.parseInt(val.match(/&H(.{2})/)![1], 16)
}

export function readColor(assColorString: string) {
  const _a = ASS_COLOR.exec(assColorString)!
  const b = _a[2]
  const g = _a[3]
  const r = _a[4]

  return {
    a: 1,
    b: Number.parseInt(b, 16),
    g: Number.parseInt(g, 16),
    r: Number.parseInt(r, 16),
  }
}

export function colorToAss(color: { r: number, g: number, b: number }): string {
  const a = 0
  const { b, g, r } = color

  return (
    `&H${
      [a, b, g, r]
        .map(x => zfill(x.toString(16).toUpperCase(), 2))
        .join('')}`
  )
}

export function colorToHtml(color: { r: number, g: number, b: number }): string {
  const { r, g, b } = color

  return (
    `#${
      [r, g, b]
        .map(x => zfill(x.toString(16), 2))
        .join('')}`
  )
}

export function toSubTime(str: string): string {
  const n: string[] = []
  let sx: string | string[] = ''
  let x = str.split(/[:.]/).map(x => Number(x))
  x = str.split(/[:.]/).map(x => Number(x))
  const frac = `0.${(`00${x[3]}`).slice(-3)}`
  sx = (x[0] * 60 * 60 + x[1] * 60 + x[2] + Number(frac)).toFixed(2)
  sx = sx.toString().split('.')
  n.unshift(sx[1])
  const total = Number(sx[0])
  n.unshift((`0${(total % 60).toString()}`).slice(-2))
  n.unshift((`0${(Math.floor(total / 60) % 60).toString()}`).slice(-2))
  n.unshift((Math.floor(total / 3600) % 60).toString())
  return `${n.slice(0, 3).join(':')}.${n[3]}`
}

export function sub2ass(task: TaskData & { presets?: Record<string, unknown>[] }): string {
  const { subtitle, style, presets = [] } = cloneDeep(task)
  const { subtitleMode } = task.option

  const Fontsize2 = Math.floor(style.Fontsize * 0.6)

  return `
[Script Info]
; // This subtitle was generated by https://aimu.app
Synch Point:1
ScriptType:v4.00+
Collisions:Normal

[V4+ Styles]
Format: ${ASS_KEYS.join(', ')}
Style: ${ASS_KEYS.map(key => (style as unknown as Record<string, unknown>)[key]).join(', ')}
${presets.map(preset => `Style: ${ASS_KEYS.map(key => preset[key]).join(', ')}`).join('\n')}

[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
${subtitle
  .map((item) => {
    const text = (item.text || '').trim()
    const text2 = (item.text2 || '').trim()

    item.text = text
    item.text2 = text2

    if (style.BorderStyle === 4) {
      item.text = item.text
        .split(/\r?\n/g)
        .map(line => `\\h${line}\\h`)
        .join('\n')
      item.text2 = item.text2
        .split(/\r?\n/g)
        .map(line => `\\h${line}\\h`)
        .join('\n')
    }

    let subText = ''
    const mainText = item.text
    let secondText = `{\\c&${style.SecondaryColour}&}${item.text2}`

    if (style.SecondaryOutlineColour) {
      secondText = `{\\3c&${style.SecondaryOutlineColour}&}${secondText}`
    }

    if (style.SecondaryBackColour) {
      secondText = `{\\4c&${style.SecondaryBackColour}&}${secondText}`
    }

    if (subtitleMode === 2 && text) {
      subText = mainText
    }

    if (subtitleMode === 3 && text2) {
      subText = secondText
    }

    if (subtitleMode === 1) {
      if (text) {
        subText = mainText
      }

      if (text2) {
        subText += `\\N{\\fs${Fontsize2}}${secondText}`
      }
    }

    const start = toSubTime(item.start!)
    const end = toSubTime(item.end!)
    const assText = subText.replace(/\r?\n/g, '\\N')
    const preset = (item as { preset?: string }).preset || 'Default'
    return `Dialogue: 0,${start},${end},${preset},NTP,0000,0000,0000,,${assText}`
  })
  .join('\n')}
    `.trim()
}

export function ass2vtt(ass: string): string {
  const re_ass = new RegExp(
    'Dialogue:\\s\\d,'
    + '(\\d+:\\d\\d:\\d\\d.\\d\\d),'
    + '(\\d+:\\d\\d:\\d\\d.\\d\\d),'
    + '([^,]*),'
    + '([^,]*),'
    + '(?:[^,]*,){4}'
    + '([\\s\\S]*)$',
    'i',
  )

  function fixTime(time = ''): string {
    return time
      .split(/[:.]/)
      .map((item, index, arr) => {
        if (index === arr.length - 1) {
          if (item.length === 1) {
            return `.${item}00`
          }
          else if (item.length === 2) {
            return `.${item}0`
          }
        }
        else {
          if (item.length === 1) {
            return (index === 0 ? '0' : ':0') + item
          }
        }

        return index === 0
          ? item
          : index === arr.length - 1
            ? `.${item}`
            : `:${item}`
      })
      .join('')
  }

  return (
    `WEBVTT\n\n${
      ass
        .split(/\r?\n/)
        .map((line) => {
          const m = line.match(re_ass)
          if (!m) return null
          return {
            start: fixTime(m[1].trim()),
            end: fixTime(m[2].trim()),
            text: m[5]
              .replace(/\{[\s\S]*?\}/g, '')
              .replace(/(\\N)/g, '\n')
              .trim()
              .split(/\r?\n/)
              .map(item => item.trim())
              .join('\n'),
          }
        })
        .filter((line): line is { start: string, end: string, text: string } => Boolean(line))
        .map((line, index) => {
          return (
            `${index + 1}\n${line.start} --> ${line.end}\n${line.text}`
          )
        })
        .filter(line => line.trim())
        .join('\n\n')}`
  )
}

export function fixSrt(srt: string): string {
  return srt.replace(/(\d\d:\d\d:\d\d)[,.](\d+)/g, (_, $1, $2) => {
    let ms = $2.slice(0, 3)
    if ($2.length === 1) {
      ms = `${$2}00`
    }
    if ($2.length === 2) {
      ms = `${$2}0`
    }
    return `${$1},${ms}`
  })
}

export function srt2vtt(srt: string): string {
  return 'WEBVTT \r\n\r\n'.concat(
    fixSrt(srt)
      .replace(/\{\\([ibu])\}/g, '</$1>')
      .replace(/\{\\([ibu])1\}/g, '<$1>')
      .replace(/\{([ibu])\}/g, '<$1>')
      .replace(/\{\/([ibu])\}/g, '</$1>')
      .replace(/(\d\d:\d\d:\d\d),(\d\d\d)/g, '$1.$2')
      .replace(/\{[\s\S]*?\}/g, '')
      .concat('\r\n\r\n'),
  )
}

export function fixSub(subs: Sub[] = []): Sub[] {
  const result: Sub[] = []

  for (let index = 0; index < subs.length; index++) {
    const sub = subs[index]

    if (sub.startTime >= sub.endTime) {
      continue
    }

    if (index === 0) {
      result.push(sub)
      continue
    }

    const prev = result[result.length - 1]
    const subTime = sub.endTime - sub.startTime
    const prevDiff = sub.startTime - prev.endTime

    if (prevDiff < 0) {
      if (prevDiff >= -0.5 && subTime >= 1) {
        sub.startTime = prev.endTime
      }
      else {
        prev.merge(sub)
        continue
      }
    }

    result.push(sub)
  }

  return result
}

export function url2sub(url: string): Promise<Sub[]> {
  return new Promise((resolve) => {
    const $video = document.createElement('video')
    const $track = document.createElement('track')
    $track.default = true
    $track.kind = 'metadata'
    $video.appendChild($track)
    $track.onerror = () => resolve([])
    $track.onload = () => {
      resolve(
        fixSub(
          Array.from($track.track.cues || [])
            .map((item) => {
              const cue = item as TextTrackCue & { text?: string }
              const startTime = cue.startTime
              const endTime = cue.endTime
              const text = cue.text || ''
              return new Sub({ startTime, endTime, text })
            })
            .filter(item => item.check),
        ),
      )
    }
    $track.src = url
  })
}

export function vtt2url(vtt: string): string {
  return URL.createObjectURL(
    new Blob([vtt], { type: 'text/vtt' }),
  )
}

export function file2sub(file: File): Promise<Sub[]> {
  return new Promise((resolve) => {
    async function handle(result: string) {
      const ext = getFileFormat(file.name)
      if (ext === 'json') {
        try {
          const sub = JSON.parse(result)
            .map((item: ConstructorParameters<typeof Sub>[0]) => new Sub(item))
            .filter((item: Sub) => item.check)
          resolve(sub)
        }
        catch {
          resolve([])
        }
      }
      else {
        const text = result.replace(/\{[\s\S]*?\}/g, '')
        switch (ext) {
          case 'vtt': {
            const url = vtt2url(text)
            const sub = await url2sub(url)
            resolve(sub)
            break
          }
          case 'ass': {
            const vtt = ass2vtt(text)
            const url = vtt2url(vtt)
            const sub = await url2sub(url)
            resolve(sub)
            break
          }
          case 'srt': {
            const vtt = srt2vtt(text)
            const url = vtt2url(vtt)
            const sub = await url2sub(url)
            resolve(sub)
            break
          }
          default:
            resolve([])
            break
        }
      }
    }

    let tryGB2312 = false
    const reader = new FileReader()

    reader.onload = () => {
      const result = reader.result as string
      if (result.includes('�') && !tryGB2312) {
        tryGB2312 = true
        reader.readAsText(file, 'GB2312')
      }
      else {
        handle(result)
      }
    }

    reader.readAsText(file)
  })
}

export function sub2vtt(sub: Sub[], mode: number): string {
  return (
    `WEBVTT\n\n${
      sub
        .map((item, index) => {
          const text
            = mode === 2
              ? item.text
              : mode === 3
                ? item.text2
                : `${item.text}\n${item.text2}`
          return `${index + 1}\n${item.start} --> ${item.end}\n${text}`
        })
        .join('\n\n')}`
  )
}

export function sub2srt(sub: Sub[], mode: number): string {
  return sub
    .map((item, index) => {
      const text
        = mode === 2
          ? item.text
          : mode === 3
            ? item.text2
            : `${item.text}\n${item.text2}`
      return `${index + 1}\n${item.start.replace('.', ',')} --> ${item.end.replace('.', ',')}\n${text}`
    })
    .join('\n\n')
}

export function sub2txt(sub: Sub[], mode: number): string {
  return sub
    .map((item) => {
      const text
        = mode === 2
          ? item.text
          : mode === 3
            ? item.text2
            : `${item.text}\n${item.text2}`
      return text
    })
    .join('\n\n')
}
